# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-CCProcessor
version:      0.06
version_from: lib/Business/CCProcessor.pm
installdirs:  site
requires:
    Carp:                          0
    CGI::FormBuilder:              0
    Test::HTML::Lint:              0
    Test::More:                    0
    Test::Perl::Critic:            0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
