---
name: Business-CCProcessor
version: 0.05
author:
  - 'Hugh Esco <hesco@campaignfoundations.com>'
abstract: Pass transaction off to secure processor
license: gpl
resources:
  license: http://www.opensource.org/licenses/gpl-license.php
requires:
  CGI::FormBuilder: 0
  Carp: 0
  Test::More: 0
  version: 0
provides:
  Business::CCProcessor:
    file: lib/Business/CCProcessor.pm
    version: 0.05
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
